name: XRayField
version: 0.6.1
author: lambdaviking
description: Prevents x-raying with some physics and math
main: snorri.main.XRayField
commands:
  xray:
    description: X-Ray stuff
    usage: /xray