name: XRayField
version: 0.1.1
author: lambdaviking
description: Prevents x-raying with some physics and math
main: snorri.main.XRayField
commands:
  test:
    description: Checks probability that players are cheating
    usage: /test [player1] [player2] ..