name: XRayField
version: 1.4.2
author: lambdaviking
description: Prevents x-raying with some physics and math
main: snorri.main.XRayField
commands:
  xray:
    description: use to see if a player is x-raying
    usage: /xray [-as] < stats <player> | test <player> [null] | trust [-r] [player] | scan [null] >